version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  jobs:
    pre_build:
      # Generate Sphinx configuration for this Jupyter Book
      - "jupyter-book config sphinx docs/"

python:
   install:
   - requirements: docs/requirements.txt
   - method: pip
     path: .

formats:
  - pdf
  - epub